// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMcOVCE4pVXXepvltMhpnhAv3lnJrUsVk',
    appId: '1:77977059621:android:f485511bce7939ad251acc',
    messagingSenderId: '77977059621',
    projectId: 'wechat-eb13a',
    storageBucket: 'wechat-eb13a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7dzLZKi1iIrxk4_gyIjz11oszMTH052s',
    appId: '1:77977059621:ios:09aeebecaf72cba5251acc',
    messagingSenderId: '77977059621',
    projectId: 'wechat-eb13a',
    storageBucket: 'wechat-eb13a.appspot.com',
    androidClientId: '77977059621-ortcm9qjk5q08rgg1ht101hvnid9669m.apps.googleusercontent.com',
    iosClientId: '77977059621-len6cac7ei6pgpln7hndck72gtdv0gnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.wechat',
  );
}
